<?php 

include("con_db.php");

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adm</title>
    <link rel="stylesheet" href="styleAdm.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <div class="page-header">
        <h1>Inscritos</h1>
    </div>
    
        <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
            <caption class="sr-only">Explanation of what this complex data table does.</caption>
            <thead>
            <tr>
                <th id="first_name" role="gridcell">Id</th>
                <th id="last_name" role="gridcell">Tutor</th>
                <th id="user_role" role="gridcell">Menor</th>
                <th role="gridcell" id="taller">Taller</th>
                <th role="gridcell" id="Grupo">Grupo</th>
                <th role="gridcell" id="Horarios">Horarios</th>
                <th role="gridcell" id="Dias">Dias</th>
                <th role="gridcell" id="materiales">Materiales</th>
                <th role="gridcell" id="celular">Celular</th>
                
                <th role="gridcell" id="direccion">Dirección</th>
                <th role="gridcell" id="fecha">Fecha</th>
                
                <th role="gridcell" id="user_actions">Actions</th>
            </tr>
            </thead>
            <tbody>

            <?php

            $sql="SELECT * from datos";
            $result=mysqli_query($conex,$sql);

            while($mostrar=mysqli_fetch_array($result)){
            ?>
                <tr>
                    <td><?php echo $mostrar['id'] ?></td>
                    <td><?php echo $mostrar['nombre'] ?></td>
                    <td><?php echo $mostrar['nombre_menor'] ?></td>
                    <td><?php echo $mostrar['taller'] ?></td>
                    <td><?php echo $mostrar['grupo'] ?></td>
                    <td><?php echo $mostrar['horario'] ?></td>
                    <td><?php echo $mostrar['dias'] ?></td>
                    <td><?php echo $mostrar['materiales'] ?></td>
                    <td><?php echo $mostrar['celular'] ?></td>
                    <td><?php echo $mostrar['direccion'] ?></td>
                    <td><?php echo $mostrar['fecha_registro'] ?></td>


                    <!-- botones -->
                    <td><button class="btn btn-primary">Edit</button> <button class="btn btn-danger">Delete</button></td>
                </tr>
                <?php
                }
                ?>
            <tbody>   
        </table>
        
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>